@startuml uml-diagram
title Appointment Booking System - Class Diagram


enum ServiceStatus {
  ACTIVE
  INACTIVE
}

enum AppointmentStatus {
  PENDING
  CONFIRMED
  CANCELLED
  COMPLETED
  NO_SHOW
}


class Service {
  +id: number
  +code: string
  +name: string
  +description: string
  +durationMinutes: number
  +minAdvanceBooking : number
  +price: number
  +currency : string
  +status: ServiceStatus
  +maxBookingsPerSlot: number
  +allowWalkIn: boolean
  +createdAt: Date
  +updatedAt: Date
}

class Appointment {
  +id: string
  +bookingCode: string
  +serviceId: string
  +customerName: string
  +customerAge : number
  +customerPhone: string
  +customerEmail : string 
  +startTime: Date
  +endTime: Date
  +status: AppointmentStatus
  +isPaid: boolean
  +note: string
  +createdAt: Date
  +updatedAt: Date
}

Service "1" -- "0..*" Appointment : has
Service ..> ServiceStatus
Appointment ..> AppointmentStatus

@enduml